# Generated by Django 2.0.5 on 2018-09-06 14:38

from django.conf import settings
from django.db import migrations, models
import select2.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.IntegerField(null=True)),
                ('comment', models.CharField(default='', max_length=512, null=True)),
                ('commented_by', models.ForeignKey(blank=True, on_delete='on_delete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active_Description', models.CharField(default='', max_length=100)),
                ('Exceting_Agency', models.CharField(default='', max_length=100)),
                ('Assigned_Date', models.DateField(blank=True, null=True)),
                ('Deadline', models.DateField(blank=True, null=True)),
                ('Associated_with', models.CharField(default='', max_length=100)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('submitted', 'Submitted')], default='', max_length=100)),
                ('Assigned_By', models.CharField(default='', max_length=100, null=True)),
                ('Progress', models.IntegerField(null=True)),
                ('Action_Required', models.ForeignKey(default='', on_delete='on_delete', to='Dictionary.Action')),
                ('Activity_Type', models.ForeignKey(default='', on_delete='on_delete', to='Dictionary.Activity')),
                ('Assigned_To', select2.fields.ManyToManyField(sorted=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
