# Generated by Django 2.0.5 on 2018-09-07 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_activity',
            name='commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete='on_delete', to=settings.AUTH_USER_MODEL),
        ),
    ]
