# Generated by Django 2.0.5 on 2018-09-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0004_comments_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_activity',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
