# Generated by Django 2.0.5 on 2018-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0005_auto_20180907_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.IntegerField(null=True)),
                ('Progress', models.IntegerField(null=True)),
                ('Progress_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pending_activity',
            name='Progress',
        ),
    ]
