# Generated by Django 2.0.5 on 2018-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0006_auto_20180910_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress_Activity',
        ),
        migrations.AddField(
            model_name='pending_activity',
            name='Progress',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pending_activity',
            name='Progress_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
