# Generated by Django 2.0.5 on 2018-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0007_auto_20180911_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_activity',
            name='Progress',
            field=models.IntegerField(default=0),
        ),
    ]
