# Generated by Django 2.0.5 on 2018-09-11 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0008_auto_20180911_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_activity',
            name='Progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
