# Generated by Django 2.0.5 on 2018-09-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0009_auto_20180911_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_activity',
            name='Action_Required',
            field=models.ForeignKey(default='', null=True, on_delete='on_delete', to='Dictionary.Action'),
        ),
    ]
