# Generated by Django 2.0.5 on 2018-09-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0010_auto_20180911_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_activity',
            name='Activity_Type',
            field=models.ForeignKey(default='', null=True, on_delete='on_delete', to='Dictionary.Activity'),
        ),
    ]
