# Generated by Django 2.0.5 on 2018-09-13 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0011_auto_20180911_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
