# Generated by Django 2.0.5 on 2018-09-13 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0012_comments_activity_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_activity',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
