# Generated by Django 2.0.5 on 2018-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0013_auto_20180913_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_activity',
            name='comment_notification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending_activity',
            name='progress_notification',
            field=models.IntegerField(default=0),
        ),
    ]
