# Generated by Django 2.0.5 on 2018-09-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0014_auto_20180914_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_activity',
            name='commented_for',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
