# Generated by Django 2.0.5 on 2018-09-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0015_comments_activity_commented_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_activity',
            name='comment_notification_by',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
