# Generated by Django 2.0.5 on 2018-09-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0017_pending_activity_progress_notification_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_activity',
            name='progress_by',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
