# Generated by Django 2.0.5 on 2018-09-16 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0018_pending_activity_progress_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_activity',
            name='progress_by',
            field=models.ForeignKey(default='', null=True, on_delete='on_delete', related_name='progress_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
