# Generated by Django 2.0.5 on 2018-09-06 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(default='', max_length=100)),
                ('user_type', models.CharField(choices=[('administration', 'Administration'), ('normal', 'Normal')], max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete='on_delete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
